# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Pite Sami spellchecker"
sje = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Pite Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
sje = "TRANSLATE: A spellchecker for Pite Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.sje"

[windows]
system_product_code = "{B8E80889-F358-4D19-841F-9829D9E41570}_is1"
legacy_product_codes = [
    { value = "A7AAB3BF-7B9B-468E-8956-739857019D2F", kind = "nsis" },
    { value = "37BB0BBF-0791-4E15-9746-E232D8E20C60", kind = "nsis" }
]
extra_locales = { sje-SE = "sje" }

[package.speller]
name = "Pite Sami"
version = "0.1.1"

[package.grammar]
name = "Pite Sami"
version = "0.1.0"

[package.tts-text-proc]
name = "Pite Sami"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
