template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "pite1240"
__REPO__ = "lang-sje"
__UND2C__ = "sje"
__UNDEFINED__ = "Pite Sami"
__UND__ = "sje"
