template = "https://github.com/giellalt/template-lang-und"
rev_id = 13
template_sha = "dd69a33be5b95bb47811959516037d6e18dc4cb2"

[replacements]
__UND2C__ = "sje"
__UNDEFINED__ = "Pite Sami"
__UND__ = "sje"
